apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: bnl-project
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
